Update BUILDING-FEDORA.md
obs-ai/obs-backgroundremoval pull request #482
Opened 2023-10-28 17:44 UTC by T0MASD

update url to new org, use shallow clone, save x3 clone time and size

```
$ time git clone https://github.com/royshil/obs-backgroundremoval.git
Cloning into 'obs-backgroundremoval'...
remote: Enumerating objects: 2081, done.
remote: Counting objects: 100% (1204/1204), done.
remote: Compressing objects: 100% (669/669), done.
remote: Total 2081 (delta 750), reused 847 (delta 521), pack-reused 877
Receiving objects: 100% (2081/2081), 56.39 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (1119/1119), done.

real	0m31.949s
user	0m2.081s
sys	0m1.675s

```

vs
```
$ time git clone https://github.com/royshil/obs-backgroundremoval.git --depth=1
Cloning into 'obs-backgroundremoval'...
remote: Enumerating objects: 257, done.
remote: Counting objects: 100% (257/257), done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 257 (delta 25), reused 152 (delta 21), pack-reused 0
Receiving objects: 100% (257/257), 24.17 MiB | 2.33 MiB/s, done.
Resolving deltas: 100% (25/25), done.

real	0m11.341s
user	0m0.779s
sys	0m0.669s
```

2023-10-28 19:19 UTC, royshil approved these changes
LGTM

2023-10-29 05:49 UTC, umireon requested changes

2023-10-29 05:49 UTC, umireon commented on docs/BUILDING-FEDORA.md
> +git clone https://github.com/obs-ai/obs-backgroundremoval.git --depth=1
```suggestion
git clone https://github.com/obs-ai/obs-backgroundremoval.git
```

2023-10-29 05:50 UTC, umireon commented
I don't think we should recommend depth=1. This will be problematic.

2023-10-29 05:51 UTC, umireon commented
Saving 20 secs does not worth specifying --depth=1.

2023-10-29 05:54 UTC, royshil commented
@umireon it's just for the build, this is in the readme, we can comment and say that it will get only the master branch without any history and that for actual development you need to `git fetch --unshallow`

2023-10-29 06:03 UTC, umireon commented
If we suggest users use the full history, all the users can build our plugin correctly and some users can use git commands without additional operation when they need to use source codes on PR.
The `--depth=1` option will require us the additional context to be added to the README and the additional context will confuse users.

IMO `--depth=1` is a very harmful option with almost no benefit. AFAIK the homebrew project had stopped using --depth=1 because it was very harmful.

2023-10-29 06:11 UTC, umireon commented
I don't want to ask Fedora users who have a build problem if their git copy is shallow or deep because this question is hard to answer.

2023-10-29 06:12 UTC, royshil commented
okay i see your point.
we can keep it as is for now and see if anyone has complaints in the future about the clone time

2023-10-29 06:15 UTC, umireon commented
I will agree with --depth=1 when cloning our repository takes 30 mins, of course!

2023-10-29 08:34 UTC, umireon approved these changes
LGTM

2023-10-29 13:34 UTC, merged